language: go

before_install:
  - go get github.com/mitchellh/gox
  - go get github.com/tcnksm/ghr

script:
  - gox -output "dist/{{.OS}}_{{.Arch}}_{{.Dir}}"
  - ghr --username shiimaxx --token $GITHUB_TOKEN --replace --prerelease pre-release dist/
